// Error Code Registry from API_STANDARDS.md

/**
 * Error codes mapped to human-readable constants
 * Format: MODULE_SEVERITY_SEQUENCE
 */
export enum ErrorCode {
    // SALES Module
    SALES_001 = 'SALES_001', // ORDER_NOT_FOUND
    SALES_002 = 'SALES_002', // ORDER_ALREADY_COMPLETED
    SALES_003 = 'SALES_003', // ORDER_ALREADY_PAID
    SALES_004 = 'SALES_004', // ORDER_ITEM_NOT_FOUND
    SALES_005 = 'SALES_005', // PAYMENT_AMOUNT_MISMATCH
    SALES_006 = 'SALES_006', // REFUND_EXCEEDS_ORIGINAL
    SALES_007 = 'SALES_007', // ORDER_ALREADY_VOIDED
    SALES_008 = 'SALES_008', // INSUFFICIENT_MANAGER_AUTH
    SALES_009 = 'SALES_009', // REGISTER_SESSION_CLOSED
    SALES_010 = 'SALES_010', // INVALID_ORDER_TYPE
    SALES_011 = 'SALES_011', // TABLE_ALREADY_OCCUPIED
    SALES_012 = 'SALES_012', // SPLIT_PAYMENT_INCOMPLETE

    // INVENTORY Module
    INV_001 = 'INV_001', // BATCH_NOT_FOUND
    INV_002 = 'INV_002', // INSUFFICIENT_STOCK
    INV_003 = 'INV_003', // BATCH_EXPIRED
    INV_004 = 'INV_004', // NEGATIVE_STOCK
    INV_005 = 'INV_005', // WAREHOUSE_INACTIVE
    INV_006 = 'INV_006', // FIFO_CALCULATION_FAILED
    INV_007 = 'INV_007', // RECIPE_NOT_FOUND
    INV_008 = 'INV_008', // INGREDIENT_STOCK_LOW
    INV_009 = 'INV_009', // PURCHASE_ORDER_LOCKED
    INV_010 = 'INV_010', // STOCK_MOVE_IMMUTABLE

    // ZATCA Module (CRITICAL)
    ZATCA_001 = 'ZATCA_001', // HASH_CHAIN_BROKEN
    ZATCA_002 = 'ZATCA_002', // INVOICE_COUNTER_SKIP
    ZATCA_003 = 'ZATCA_003', // XML_GENERATION_FAILED
    ZATCA_004 = 'ZATCA_004', // QR_CODE_INVALID
    ZATCA_005 = 'ZATCA_005', // SIGNATURE_MISSING
    ZATCA_006 = 'ZATCA_006', // SUBMISSION_FAILED
    ZATCA_007 = 'ZATCA_007', // UUID_DUPLICATE
    ZATCA_008 = 'ZATCA_008', // CUSTOMER_TAX_REQUIRED

    // CASH Module
    CASH_001 = 'CASH_001', // SESSION_NOT_OPEN
    CASH_002 = 'CASH_002', // SESSION_ALREADY_OPEN
    CASH_003 = 'CASH_003', // CASH_DISCREPANCY
    CASH_004 = 'CASH_004', // NEGATIVE_FLOAT
    CASH_005 = 'CASH_005', // PAYOUT_EXCEEDS_CASH

    // KITCHEN Module
    KIT_001 = 'KIT_001', // TICKET_NOT_FOUND
    KIT_002 = 'KIT_002', // STATION_INACTIVE
    KIT_003 = 'KIT_003', // TICKET_ALREADY_SERVED
    KIT_004 = 'KIT_004', // PRINTER_OFFLINE

    // PRODUCT Module
    PROD_001 = 'PROD_001', // PRODUCT_NOT_FOUND
    PROD_002 = 'PROD_002', // SKU_DUPLICATE
    PROD_003 = 'PROD_003', // MODIFIER_REQUIRED
    PROD_004 = 'PROD_004', // MODIFIER_MIN_NOT_MET
    PROD_005 = 'PROD_005', // MODIFIER_MAX_EXCEEDED
    PROD_006 = 'PROD_006', // PRODUCT_INACTIVE

    // CRM Module
    CRM_001 = 'CRM_001', // CUSTOMER_NOT_FOUND
    CRM_002 = 'CRM_002', // CREDIT_LIMIT_EXCEEDED
    CRM_003 = 'CRM_003', // PHONE_DUPLICATE
    CRM_004 = 'CRM_004', // INSUFFICIENT_LOYALTY_POINTS

    // AUTH Module
    AUTH_001 = 'AUTH_001', // INVALID_CREDENTIALS
    AUTH_002 = 'AUTH_002', // USER_NOT_FOUND
    AUTH_003 = 'AUTH_003', // USER_INACTIVE
    AUTH_004 = 'AUTH_004', // TOKEN_EXPIRED
    AUTH_005 = 'AUTH_005', // INSUFFICIENT_PERMISSIONS
    AUTH_006 = 'AUTH_006', // PIN_CODE_INVALID

    // SYSTEM Module
    SYS_001 = 'SYS_001', // DEVICE_NOT_REGISTERED
    SYS_002 = 'SYS_002', // DEVICE_OFFLINE
    SYS_003 = 'SYS_003', // TRANSACTION_DEADLOCK
    SYS_004 = 'SYS_004', // TRANSACTION_ROLLBACK
    SYS_005 = 'SYS_005', // CONFIGURATION_MISSING
}

/**
 * Error message keys for i18n
 */
export enum ErrorMessageKey {
    ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
    ORDER_ALREADY_COMPLETED = 'ORDER_ALREADY_COMPLETED',
    ORDER_ALREADY_PAID = 'ORDER_ALREADY_PAID',
    INSUFFICIENT_STOCK = 'INSUFFICIENT_STOCK',
    HASH_CHAIN_BROKEN = 'HASH_CHAIN_BROKEN',
    // ... add more as needed
}

/**
 * Critical error codes that require system halt
 */
export const CRITICAL_ERROR_CODES = [
    ErrorCode.ZATCA_001, // Hash chain broken
    ErrorCode.SYS_003, // Transaction deadlock
    ErrorCode.SYS_004, // Transaction rollback
];

/**
 * Check if error code is critical
 */
export function isCriticalError(code: string): boolean {
    return CRITICAL_ERROR_CODES.includes(code as ErrorCode);
}
